import os

AZURE_STORAGE_ACCOUNT_NAME = ""
AZURE_STORAGE_ACCOUNT_KEY = ""
AZURE_BLOB_CONTAINER_NAME = ""
AZURE_FILE_SHARE_NAME = ""
# Generate connection string
AZURE_CONNECTION_STRING = ""

